- name: golfball events
  hosts: localhost
  sources:
    - kubealex.eda.mqtt:
        host: "{{ mqtt_host }}"
        port: 1883
        topic: 'ansible-golfs/golfball/#'
        username: "{{ mqtt_username }}"
        password: "{{ mqtt_password }}"

  rules:
    - name: Putt made
      condition: event.data == "ST_MAGNET_STOP" and event.stroke > 1
      action:
        run_workflow_template:
          name: "Golf Demo Workflow"
          organization: Default
          job_args:
            extra_vars:
              slack_message: "*New putt made in {{ event.stroke }} strokes!* \n\n Event received at {{ event.meta.received_at }} by #eventdriven #ansible at London Summit Connect"
              gif_list: hole_in_more

    - name: Hole in one
      condition: event.data == "ST_MAGNET_STOP" and event.stroke == 1
      action:
        run_workflow_template:
          name: "Golf Demo Workflow"
          organization: Default
          job_args:
            extra_vars:
              slack_message: "*Talk about a hole in {{ event.stroke }}!* \n\n Event received at {{ event.meta.received_at }} by #eventdriven #ansible at London Summit Connect"
              gif_list: hole_in_one
