version: 3

images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/de-minimal-rhel8:latest'

dependencies:
  galaxy:
    collections:
      - ansible.eda
      - kubealex.eda
  system:
    - pkgconf-pkg-config [platform:rpm]
    - systemd-devel [platform:rpm]
    - gcc [platform:rpm]
    - python3.11-devel [platform:rpm]
  python_interpreter:
    package_system: "python3.11"
  python:
    - aiomqtt

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  append_final:
    - ENV PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.11/site-packages
