---

- hosts: localhost
  gather_facts: false
  tasks:
  - name: send putt message to slack
    community.general.slack:
      token: "{{ slack_token }}"
      channel: "{{ slack_channel }}"
      msg: "{{ slack_message }}"
      blocks:
      - type: image
        alt_text: test
        image_url: "{{ slack_image_url }}"
